### ISSUE TITLE
MacOS restricts access to /usr/lib (even with sudo.)

### ISSUE THREAD

**Issue by Intel-i80486-DX4** [TudbuT/isbpl#2]
iMac:isbpl-master user$ sudo sh ./setup.sh 
Password:
mkdir: /usr/lib/isbpl: Operation not permitted
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
iMac:isbpl-master user$

**Comment by TudbuT** [comment]
try adding
ISBPL_PATH=(path to clone of this repo)
to your default environment

**Comment by Intel-i80486-DX4** [comment]
done, now kindly check Your fucking reddit more often.
